import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Blogcard from '../components/Blogcard'
import Businesscard from '../components/Businesscard'
import Features from '../components/features'
import FormInput from '../components/formInput'
import Header from '../components/Header'
import Jobcard from '../components/Jobcard'
import ProductCard from '../components/productCard'
import Testimonial from '../components/testimonial'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Riby Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <Header />
        <Features/> */}
        {/* <Blogcard/>
        <FormInput />
        <Jobcard/> */}
        {/* <ProductCard />
        <Businesscard/> */}
        <Testimonial/>
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
