import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import ChatWidget from '../components/atoms/ChatWidget'
import Header from '../components/atoms/Header'
import Business from '../components/molecules/Business'
import Footer from '../components/molecules/Footer'
import Hero from '../components/molecules/Hero'
import Product from '../components/molecules/Product'

const Home: NextPage = () =>
{

  
  return (
    <div>
      <Head>
        <title>Riby Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='w-full h-fit'>

        <Header />
        <Hero />
        <Product />
        <Business />
        <Footer />
        <ChatWidget/>
      </main>
    </div>
  )
}

export default Home
